os: Visual Studio 2015

environment:
  matrix:
    - nodejs_version: "8"
    - nodejs_version: "9"
    - nodejs_version: "10"

  # PYTHON2.7 REQUIRED FOR NODE-GYP & ELECTRON
  PYTHON2: "C:\\Python27"
  PYTHON2_VERSION: "2.7.9"
  PYTHON2_ARCH: "64"

  PIP2: C:\\Python27\Scripts\pip

  npm_config_arch: x64

platform: x64

configuration: Release

init:
  - cmd: node --version
  - cmd: npm --version

  - "ECHO Installed SDKs:"
  - ps: "ls \"C:/Program Files/Microsoft SDKs/Windows\""

  - cmd: ECHO Processor architecture - %PROCESSOR_ARCHITECTURE%
  - cmd: wmic OS get OSArchitecture
  - cmd: npm config set msvs_version 2015 --global

  - cmd: ECHO %PYTHON2% %PYTHON2_VERSION% %PYTHON2_ARCH%
  - cmd: "%PYTHON2%\\python --version"
  - cmd: "%PYTHON2%\\python -c \"import struct; print(struct.calcsize('P') * 8)\""
  - cmd: "%PYTHON2%\\python -m pip install --upgrade pip"

  - ps: Install-Product node $env:nodejs_version
  - cmd: node --version
  - cmd: npm --version
    # CRITICAL FOR NODE-GYP TO WORK
  - cmd: npm -g install npm@latest
  - cmd: npm --version

  # SET THE RELEVANT PYTHON AND PIP LOCATIONS IN THE PATH
  - cmd: set PATH=%PYTHON2%;%PYTHON2%\scripts;%PATH%
  - cmd: ECHO Path - %PATH%

install:
  - cmd: "%PIP2% freeze"
  - cmd: npm config list
  - cmd: npm config set python %PYTHON2%\python.exe --global

  - npm run setup
  - npm run test

build: off
